#!/bin/sh

# Downloads bitfile to an SP605 board in batch, using Impact from Xilinx ISE

if [ ! -r "${1}" ]; then
  echo "Usage: $0 filename.bit" >&2
  exit 1
fi

set -e
test -r $XILINX_SETTINGS && . $XILINX_SETTINGS
test -d $XILINX

# don't use -v switch to verify chip, since I don't create a .msk file.
# See Xilinx Answer Record 22228.
echo "
setMode -bs
setCable -port auto
Identify
assignFile -p 2 -file \"${1}\"
Program -p 2 -e -parallel -master -internalClk -clkFreq 40 -defaultVersion 0
quit" | impact -batch
