reg_data_list_of_dicts = [
    {'name': 'mode1_foffset', 'addr': 0, 'value': 5.0, 'vmin': 0, 'vmax': 10, 'unit': 'Hz'},
    {'name': 'mode1_Q1', 'addr': 0, 'value': 8.1e4, 'vmin': 0, 'vmax': 1e5, 'unit': ''},
    {'name': 'mmode1_freq', 'addr': 0, 'value': 30e3, 'vmin': 0, 'vmax': 5e4, 'unit': 'Hz'},
    {'name': 'mmode1_Q', 'addr': 0, 'value': 5.0, 'vmin': 1.0, 'vmax': 10, 'unit': ''},
    {'name': 'net1_coupling', 'addr': 0, 'value': 100, 'vmin': 0, 'vmax': 1000, 'unit': ''},
    {'name': 'net2_coupling', 'addr': 0, 'value': 120, 'vmin': 0, 'vmax': 1000, 'unit': ''},
    {'name': 'net3_coupling', 'addr': 0, 'value': 150, 'vmin': 0, 'vmax': 1000, 'unit': ''},
    {'name': 'sel_en', 'addr': 26, 'value': 1, 'vmin': 0, 'vmax': 1, 'unit': ''},
    {'name': 'set_X', 'addr': 32, 'value': 20000, 'vmin': 0, 'vmax': 32767, 'unit': ''},
    {'name': 'set_P', 'addr': 33, 'value': 0, 'vmin': -131072, 'vmax': 131071, 'unit': ''},
    {'name': 'k_PA', 'addr': 30, 'value': -200, 'vmin': -1000, 'vmax': 0, 'unit': ''},
    {'name': 'k_PP', 'addr': 31, 'value': 200, 'vmin': 0, 'vmax': 1000, 'unit': ''},
    {'name': 'maxq', 'addr': 37, 'value': 0, 'vmin': 0, 'vmax': 10000, 'unit': ''},
    {'name': 'ph_offset', 'addr': 24, 'value': -84000, 'vmin': -131072, 'vmax': 131071, 'unit': ''},
    {'name': 'amp_max', 'addr': 7, 'value': 22640, 'vmin': 0, 'vmax': 1e5, 'unit': ''},
    {'name': 'fwd_phase_shift', 'addr': 0, 'value': 0, 'vmin': 0, 'vmax': 360, 'unit': ''},
    {'name': 'rfl_phase_shift', 'addr': 0, 'value': 0, 'vmin': 0, 'vmax': 360, 'unit': ''},
    {'name': 'cav_phase_shift', 'addr': 0, 'value': 360, 'vmin': 0, 'vmax': 360, 'unit': ''},
    {'name': 'duration', 'addr': 3, 'value': 300, 'vmin': 0, 'vmax': 1e4, 'unit': ''},
    {'name': 'PRNG_en', 'addr': 3, 'value': 1, 'vmin': 0, 'vmax': 1, 'unit': ''},
    {'name': 'piezo_dc', 'addr': 22, 'value': 0, 'vmin': -2e3, 'vmax': 1e3, 'unit': ''}
]
