// parse_vfile  resonator.v
// found output address in module resonator, base=prop_const
// machine-generated by newad.py
`ifdef LB_DECODE_resonator
`include "addr_map_resonator.vh"
`define AUTOMATIC_self input lb_clk, input [31:0] lb_data, input lb_write, input [14:0] lb_addr
`define AUTOMATIC_decode\

`else
`define AUTOMATIC_self 
`define AUTOMATIC_decode
`endif
